jobs:
  include:
  - stage: test
    language: rust
    os: linux
    rust: nightly
    before_install:
    - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y
    - sudo apt-get update
    - sudo apt-get install -y libgdal-dev
    - export GDAL_STATIC=1
    script:
    - cargo build --workspace
    - cargo test --workspace -- --test-threads 1
    services:
    - redis
  - stage: test
    language: node_js
    node_js: 13.8
    install:
    - npm install
    script: bash ./format.sh check
  - stage: deploy staging
    language: rust
    os: linux
    dist: bionic
    rust: nightly
    before_install:
      - nvm install 13.8
      - openssl aes-256-cbc -K $encrypted_be519dac41c7_key -iv $encrypted_be519dac41c7_iv
        -in travis_id_rsa.enc -out ./travis_id_rsa -d
      - chmod 600 travis_id_rsa
      - echo "$SERVER_PUBLIC_SSH" >> $HOME/.ssh/known_hosts
      - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y
      - sudo apt-get update
      - sudo apt-get install libgdal-dev
    install:
      - npm i
      - npm i webpack-cli
    script:
      - export GDAL_STATIC=1
      - cargo build --release
      - npm run build_prod
      - ssh -i travis_id_rsa staging@laps.website sudo systemctl stop staging.service
      - scp -r -i travis_id_rsa dist config target/release/laps Rocket.toml staging@laps.website:~
      - ssh -i travis_id_rsa staging@laps.website sudo systemctl restart staging.service
  - stage: deploy production
    language: rust
    rust: nightly
    os: linux
    dist: bionic
    before_install:
      - nvm install 13.8
      - openssl aes-256-cbc -K $encrypted_be519dac41c7_key -iv $encrypted_be519dac41c7_iv
        -in travis_id_rsa.enc -out ./travis_id_rsa -d
      - chmod 600 travis_id_rsa
      - echo "$SERVER_PUBLIC_SSH" >> $HOME/.ssh/known_hosts
      - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y
      - sudo apt-get update
      - sudo apt-get install libgdal-dev
    install:
      - npm i
      - npm i webpack-cli
    script:
      - export GDAL_STATIC=1
      - cargo build --release
      - npm run build_prod
      - ssh -i travis_id_rsa production@laps.website sudo systemctl stop production.service
      - scp -r -i travis_id_rsa dist config target/release/laps Rocket.toml production@laps.website:~
      - ssh -i travis_id_rsa staging@laps.website sudo systemctl restart production.service
stages:
  - test
  - name: deploy staging
    if: branch = staging
  - name: deploy production
    if: branch = production
