matrix:
  include:
    - language: rust
      rust:
        - nightly
      script:
        - cargo test
      services:
        - redis-server
    - language: node_js
      node_js:
        - 13.8
      install:
        - npm install
      script: bash ./travis.sh
