# Rocket.toml: Rocket config file for the backend.
# Author: Håkon Jordet
# Copyright (c) 2020 LAPS Group
# Distributed under the zlib licence, see LICENCE.

[staging]
address = "0.0.0.0"
port = 8001
log = "normal"
limits = { forms = 4096 }

[production]
address = "0.0.0.0"
port = 8002
limits = { forms = 4096 }
